MusicApp/config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:index, :show, :new, :create ]
  resource :session, only: [:new, :create, :destroy]

  resources :bands, :albums, :tracks

end

MusicApp/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  live       :boolean          default(FALSE), not null
#  band_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ActiveRecord::Base
  validates :name, presence: true
  validates :band_id, presence: true

  belongs_to :band
  has_many :tracks
end

MusicApp/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ActiveRecord::Base
  validates :name, presence: true

  has_many :albums
  has_many :tracks, through: :albums

end

MusicApp/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  bonus      :boolean          default(FALSE), not null
#  lyrics     :text             not null
#  album_id   :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ActiveRecord::Base
  validates :name, :lyrics, :album_id, presence: true

  belongs_to :album
  has_one :band, through: :album
end

MusicApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true

  validates :password, length: {minimum: 6, allow_nil: true}

  validates :session_token, null: false, uniqueness: true
  after_initialize :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    SecureRandom.urlsafe_base64(64)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    if user && user.is_password?(password)
      user
    else
      nil
    end
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

MusicApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_user!
  
  def index
    @albums = Album.all
    render :index
  end

  def show
    @album = Album.find_by(id: params[:id])
    render :show
  end

  def new
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(band_params)

    if @album.save
      redirect_to album_url(@album)
    else

    end
  end

  def album_params
    params.require(:album).permit(:name, :live, :band_id)
  end

end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :logged_in?

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !current_user.nil?
    # session[:session_token] == current_user.session_token
  end

  def log_in_user!(user)

    session[:session_token] = user.reset_session_token!
  end

  def log_out_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_user!
    redirect_to new_session_url if current_user.nil?
  end
end

MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  # before_action :set_band, only: [:show, :edit, :update, :destroy]

  # GET /bands
  # GET /bands.json
  def index
    @bands = Band.all
    render :index
  end

  # GET /bands/1
  # GET /bands/1.json
  def show
    @band = Band.find_by(id: params[:id])
    render :show
  end

  # GET /bands/new
  def new
    @band = Band.new
    render :new
  end

  # POST /bands
  # POST /bands.json
  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  # GET /bands/1/edit
  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  # PATCH/PUT /bands/1
  # PATCH/PUT /bands/1.json
  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  # DELETE /bands/1
  # DELETE /bands/1.json
  def destroy
    @band.destroy

  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def band_params
    params.require(:band).permit(:name)
  end
end

MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by(email: session_params[:email])
    if @user && @user.is_password?(session_params[:password])
      log_in_user!(@user)
      # session[:session_token] = @user.reset_session_token!
      redirect_to user_url(@user)
    else
      # flash.now = @user.errors.full_messages
      render text: "something went wrong"
    end

  end

  def destroy
    log_out_user!
    redirect_to new_session_url
  end

  def session_params
    params.require(:user).permit(:email, :password)
  end

end

MusicApp/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :require_user!

  def index
    @tracks = Track.all
    render :index
  end

  def show
    @track = Track.find_by(id: params[:id])
    render :show
  end

  def new
    @track = Track.new
    render :new
  end

  def create
    @track = Track.new(band_params)

    if @track.save
      redirect_to track_url(@track)
    else

    end
  end

  def track_params
    params.require(:track).permit(:name, :lyrics, :bonus, :album_id)
  end

end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    render :index
  end

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      #need error handling, use flash.now[:errors] = @user.errors.full_messages
    end
     #will need to change this render once i have a music db set up
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
end

MusicApp/app/helpers/bands_helper.rb
module BandsHelper
end

MusicApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

MusicApp/app/helpers/users_helper.rb
module UsersHelper
end

MusicApp/app/views/albums/index.html.erb
<h1> All Albums </h1>

<ul>
  <% @albums.each do |album| %>
  <li> <%= album.name %> </li>
  <% end %>
</ul>

MusicApp/app/views/albums/new.html.erb
<h1> Create a new album listing </h1>


<form action=" <%=  %> " method="post">

<!-- drop down for band name -->
  <label for="band">Band Name</label>
  <select name="album[band_id]" id="band">
    <% Band.all.each do |band| %>
      <option value="<%= band.id %>" <%= "selected" if album.band_id == band.id %> >
        <%= band.name %>
      </option>
    <% end %>
  </select>

<!-- radio buttons for live or studio album -->
  <label for="live">Live</label>
  <input type="radio" name="album[live]" id="live" <%= "checked" if album.live%> >

  <label for="studio">Studio</label>
  <input type="radio" name="album[live]" id="studio" <%= "checked" unless album.live%> >

  <input type="submit" value="submit album">

</form>

MusicApp/app/views/albums/show.html.erb
<h1> <%= @album.name %> </h1>

<br>
<label for="tracks">Tracks</label>
<ul id="tracks">
  <% @album.tracks.each do |track| %>
    <li> <%= track.name %> </li>
  <% end %>
</ul>

MusicApp/app/views/bands/_form.html.erb
<% action = (band.persisted? ? band_url(band) : bands_url) %>
<% method = (band.persisted? ? :patch : :post) %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">

  <label for="band">Band Name</label>
  <input type="text" name="band[name]" value=" <%= band.name.nil? ? "" : band.name %> ">

  <input type="submit" value="submit">
</form>

MusicApp/app/views/bands/edit.html.erb
<h1>Editing Band</h1>

<%= render 'form' %>

<%= link_to 'Show', @band %> |
<%= link_to 'Back', bands_path %>

MusicApp/app/views/bands/index.html.erb
<h1> All Bands </h1>

<ul>
  <% @bands.each do |band| %>
  <li> <%= link_to(band.name, band_url(band)) %> </li>
  <% end %>
</ul>

MusicApp/app/views/bands/new.html.erb
<h1> Add a band to the database </h1>

<%= render "form", band: @band %>

<%= link_to 'Back', bands_path %>

MusicApp/app/views/bands/show.html.erb
<h1> <%= @band.name %> </h1>

<br>
<label for="albums">Albums</label>
<ul id="albums">
  <% @band.albums.each do |album| %>
    <li> <%= link_to(album.name, album_url(album)) %> </li>
  <% end %>
</ul>

MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <% if logged_in? %>
    <%= "Logged in as #{current_user.email} "%>
    <%= button_to "sign out", session_url, method: "delete" %>
  <% else %>
    <%= "Not logged in"%>
    <%= link_to "log in", new_session_url %>
  <% end %>
</header>
<%= yield %>

</body>
</html>

MusicApp/app/views/users/index.html.erb
<h1> Index of all users </h1>

<ul>
  <% @users.each do |user| %>
    <li> <%= user.email %> </li> 
  <% end %>
</ul>

MusicApp/app/views/users/new.html.erb
<h1> User Sign Up Page </h1>


<form action="<%= users_url %>" method="post">
  <label for="email">Email: </label>
  <input type="text" name="user[email]" id="email">

  <br>

  <label for="password">Password: </label>
  <input type="text" name="user[password]" id="password">

  <br>

  <input type="submit" value="create user">

</form>

MusicApp/app/views/users/show.html.erb
<h1>  User: <%= @user.email %> </h1>