MusicApp_solution/config/routes.rb
Musicapp::Application.routes.draw do


  root to: redirect("/bands")

  resource :session, only: [:create, :destroy, :new]
  resources :users, only: [:create, :new, :show] do
    get :activate, on: :collection
  end

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :destroy, :edit, :show, :update] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :destroy, :edit, :show, :update]

  resources :notes, only: [:create, :destroy]
end

MusicApp_solution/app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :album
  has_one :band, through: :album, source: :band
  has_many :notes, dependent: :destroy

  validates :album, :lyrics, :name, :ord, presence: true

  # can't use presence validation with boolean field
  validates :bonus, inclusion: { in: [true, false] }
  validates :ord, uniqueness: { scope: :album_id }
end

MusicApp_solution/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :require_user!

  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to track_url(@track)
    else
      @album = @track.album
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    redirect_to album_url(@track.album_id)
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def new
    @album = Album.find(params[:album_id])
    @track = Track.new(album_id: params[:album_id])
    render :new
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def update
    @track = Track.find(params[:id])
    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  private
  def track_params
    params.require(:track).permit(:album_id, :bonus, :lyrics, :name, :ord)
  end
end

MusicApp_solution/app/views/tracks/_form.html.erb
<% action_url = track.persisted? ? track_url(track) : tracks_url %>
<% http_method = track.persisted? ? "PATCH" : "POST" %>


<form action="<%= action_url %>" method="POST" %>
  <input type="hidden" name="_method" value="<%= http_method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

<p>
  <label>Name
    <input type="text" name="track[name]" value="<%= track.name %>">
  </label>
</p>

<p>
  <label>Album
    <select name="track[album_id]">
      <% Album.all.each do |album| %>
        <option
          <%= "selected" if track.album_id == album.id %>
          value="<%= album.id %>">
            <%= album.name %>
        </option>
      <% end %>
    </select>
  </label>
</p>

<p>
  <label>Ord
  <input type="number" name="track[ord]" value="<%= track.ord %>">
  </label>
</p>

<p>
  <input
    type="radio"
    name="track[bonus]"
    value="f"
    id="track_bonus_f"
    <%= "checked" if !track.bonus %>>
  <label for="track_bonus_f">Standard</label>
  <br>
  <input
    type="radio"
    name="track[bonus]"
    value="t"
    id="track_bonus_t"
    <%= "checked" if track.bonus %>>
  <label for="track_bonus_t">Bonus</label>
</p>

<p>
  <label for="track_lyrics">Lyrics</label><br>
  <textarea id="track_lyrics"
    rows="10" cols="40"
    name="track[lyrics]"><%= track.lyrics %></textarea>
</p>

  <input type="submit">
</form>

MusicApp_solution/app/views/tracks/edit.html.erb
<h1>Edit <%= @track.name %></h1>

<%= render "form", track: @track %>

MusicApp_solution/app/views/tracks/new.html.erb
<h1>New <%= @album.name %> Track</h1>

<%= render "form", track: @track %>

MusicApp_solution/app/views/tracks/show.html.erb
<h1><%= @track.name %></h1>

<%= ugly_lyrics(@track.lyrics) %>

<%= render "note/form", track: @track %>

<h2>Notes</h2>
<% @track.notes.each do |note| %>
  <%= render "note/note", note: note %>
<% end %>


<h4>Links</h4>
<ul>
  <li><%= link_to "Edit Track", edit_track_url(@track) %></li>
  <li><%= link_to "Delete Track", track_url(@track), method: :delete %></li>
  <li><%= link_to @track.album.name, album_url(@track.album) %></li>
</ul>